<?php

$first_name = [
    'Alice',
    'Miguel',
    'Sophia',
    'Arthur',
    'Helena',
    'Bernardo',
    'Valentina',
    'Heitor',
    'Laura',
    'Davi',
    'Isabella',
    'Lorenzo',
    'Manuela',
    'Théo',
    'Júlia',
    'Pedro',
    'Heloísa',
    'Gabriel',
    'Luiza',
    'Enzo',
    'Maria Luiza',
    'Matheus',
    'Lorena',
    'Lucas',
    'Lívia',
    'Benjamin',
    'Giovanna',
    'Nicolas',
    'Maria Eduarda',
    'Guilherme',
    'Beatriz',
    'Rafael',
    'Maria Clara',
    'Joaquim',
    'Cecília',
    'Samuel',
    'Eloá',
    'Enzo Gabriel',
    'Lara',
    'João Miguel',
    'Maria Júlia',
    'Henrique',
    'Isadora',
    'Gustavo',
    'Mariana',
    'Murilo',
    'Emanuelly',
    'Pedro Henrique',
    'Ana Júlia',
    'Pietro',
    'Ana Luiza',
    'Lucca',
    'Ana Clara',
    'Felipe',
    'Melissa',
    'João Pedro',
    'Yasmin',
    'Isaac',
    'Maria Alice',
    'Benício',
    'Isabelly',
    'Daniel',
    'Lavínia',
    'Anthony',
    'Esther',
    'Leonardo',
    'Sarah',
    'Davi Lucca',
    'Elisa',
    'Bryan',
    'Antonella',
    'Eduardo',
    'Rafaela',
    'João Lucas',
    'Maria Cecília',
    'Victor',
    'Liz',
    'João',
    'Marina',
    'Cauã',
    'Nicole',
    'Antônio',
    'Maitê',
    'Vicente',
    'Isis',
    'Caleb',
    'Alícia',
    'Gael',
    'Luna',
    'Bento',
    'Rebeca',
    'Caio',
    'Agatha',
    'Emanuel',
    'Letícia',
    'Vinícius',
    'Maria-',
    'João Guilherme',
    'Gabriela',
    'Davi Lucas',
    'Ana Laura',
    'Noah',
    'Catarina',
    'João Gabriel',
    'Clara',
    'João Victor',
    'Ana Beatriz',
    'Luiz Miguel',
    'Vitória',
    'Francisco',
    'Olívia',
    'Kaique',
    'Maria Fernanda',
    'Otávio',
    'Emilly',
    'Augusto',
    'Maria Valentina',
    'Levi',
    'Milena',
    'Yuri',
    'Maria Helena',
    'Enrico',
    'Bianca',
    'Thiago',
    'Larissa',
    'Ian',
    'Mirella',
    'Victor Hugo',
    'Maria Flor',
    'Thomas',
    'Allana',
    'Henry',
    'Ana Sophia',
    'Luiz Felipe',
    'Clarice',
    'Ryan',
    'Pietra',
    'Arthur Miguel',
    'Maria Vitória',
    'Davi Luiz',
    'Maya',
    'Nathan',
    'Laís',
    'Pedro Lucas',
    'Ayla',
    'Davi Miguel',
    'Ana Lívia',
    'Raul',
    'Eduarda',
    'Pedro Miguel',
    'Mariah',
    'Luiz Henrique',
    'Stella',
    'Luan',
    'Ana',
    'Erick',
    'Gabrielly',
    'Martin',
    'Sophie',
    'Bruno',
    'Carolina',
    'Rodrigo',
    'Maria Laura',
    'Luiz Gustavo',
    'Maria Heloísa',
    'Arthur Gabriel',
    'Maria Sophia',
    'Breno',
    'Fernanda',
    'Kauê',
    'Malu',
    'Enzo Miguel',
    'Analu',
    'Fernando',
    'Amanda',
    'Arthur Henrique',
    'Aurora',
    'Luiz Otávio',
    'Maria Isis',
    'Carlos Eduardo',
    'Louise',
    'Tomás',
    'Heloise',
    'Lucas Gabriel',
    'Ana Vitória',
    'André',
    'Ana Cecília',
    'José',
    'Ana Liz',
    'Yago',
    'Joana',
    'Danilo',
    'Luana',
    'Anthony Gabriel',
    'Antônia',
    'Ruan',
    'Isabel',
    'Miguel Henrique',
    'Bruna',
    'Oliver',
];


$last_name = [
    'Almeida',
    'Alves',
    'Amorim',
    'Azevedo',
    'Aguiar',
    'Brito',
    'Barbosa',
    'Barcellos',
    'Barreto',
    'Batista',
    'Bernardes',
    'Betini',
    'Boldrine',
    'Borges',
    'Braga',
    'Breda',
    'Brianezi',
    'Brito',
    'Bruneli',
    'Buzatto',
    'Calmon',
    'Campos',
    'Correia',
    'Costa',
    'Cardozo',
    'Carneiro',
    'Carvalho',
    'Cavalcanti',
    'Cerqueira',
    'Coelho',
    'Correia',
    'Coutinho',
    'Fagundes',
    'de Almeida',
    'de Azevedo',
    'de Queiroz',
    'de Vasconcellos',
    'de Jesus',
    'de Souza',
    'de Avila',
    'da Silva',
    'de Assis',
    'dos Santos',
    'da Cunha',
    'da Gloria',
    'da Rocha',
    'de Oliveira',
    'de Andrades',
    'do Sacramento',
    'Azedias',
    'Chaves',
    'Godoy',
    'Kardin',
    'Nardi',
    'Pierro',
    'Girolamo',
    'Puppo',
    'Lago',
    'Donati',
    'Ebani',
    'Espinola',
    'Filete',
    'Faroni',
    'Ferrarese',
    'Fiorot',
    'Fornazier',
    'Frattini',
    'Freyre',
    'Gaiotto',
    'Gobbi',
    'Granzotto',
    'Kiepper',
    'Kister',
    'Lans',
    'Lanes',
    'Lorenzoni',
    'Carlos Eduardo',
    'Louise',
    'Lovatti',
    'Lucca',
    'Lucas Gabriel',
    'Marquioro',
    'Mortensen',
    'Mazoco',
    'Nicolini',
    'Orletti',
    'Pagani',
    'Paresqui',
    'Pastore',
    'Piai',
    'Pitanga',
    'Prates',
    'Resende',
    'Riatto',
    'Rizzo',
    'Salazar',
    'Scharra',
    'Esteves',
    'Farias',
    'Fazoli',
    'Fonseca',
    'Fernandes',
    'Fontes',
    'Fontana',
    'Fraga',
    'Freitas',
    'Gasparotto',
    'Gomes',
    'Guerra',
    'Leite',
    'Lemos',
    'Leonardes',
    'Lisboa',
    'Lopes',
    'Lozano',
    'Luca',
    'Machado',
    'Macedo',
    'Magrini',
    'Malta',
    'Marett',
    'Marinho',
    'Mascarello',
    'Matos',
    'Medeiros',
    'Menezes',
    'Mesquita',
    'Monteiro',
    'Moura',
    'Netto',
    'Nogueira',
    'Nunes',
    'Novais',
    'Oliveira',
    'Pereira',
    'Pacheco',
    'Passos',
    'Peixoto',
    'Penha',
    'Pontes',
    'Rabello',
    'Ramos',
    'Reis',
    'Ribeiro',
    'Rigotto',
    'Rocha',
    'Rosa',
    'Santos',
    'Rebeca',
    'Rossi',
    'Salles',
    'Sacramento',
    'Salgado',
    'Sampaio',
    'Sangali',
    'Santana',
    'Santos',
    'Santiago',
    'Siciliano',
    'Soares',
    'Teves',
    'Tavares',
    'Tedesco',
    'Toledo',
    'Torres',
    'Toscano',
    'Vitória',
    'Viana',
    'Vieira',
    'Vaccari',
    'Valiati',
    'Valle',
    'Varella',
    'Vaz',
    'Veloso',
    'Ventura',
    'Venturini',
    'Vereza',
    'Viana',
    'Villa',
    'Villares',
    'Zerboni',
    'Zanatta',
    'Amato',
    'Antunes',
    'Armani',
    'Bellon',
    'Barone',
    'Bassani',
    'Bergami',
    'Biazate',
    'Botelho',
    'Buzon',
    'Calegari',
    'Camatta',
    'Carnielle',
    'Catellan',
    'Cecotti',
    'Contarini',
    'Crozatti',
];